const data = [
  {
    pid: "1",
    name: "PrintVendo",
    tagline: "School Printing vendo machine",
    color: "#c2c880",
    textcolor: "black",
    time: "5 months",
    cover_image: "../mockups/PrintVendo1.jpg",
    web_images: [
      "../projects/PrintOption.png",
      "../projects/LoadFiles.png",
      "../projects/PPTOption.png",
      "../projects/PrintProperties.png",
      "../projects/SummaryConfirm.png",
      "../projects/PrintOption.png",
      "../projects/InsertFlashDrive.png",
      "../projects/FPrintProperties.png",
      "../projects/Summary.png",
    ],
    mob_images: [
      "../projects/WebApp.jpg",
      "../projects/ChooseFile.jpg",
      "../projects/mobileUpload.jpg",
    ],
    tech_images: [
      "../skills/Sharp.png",
      "../skills/VisualBasic.png",
      "../skills/Arduino2.png",
      "../skills/python.png",
      "../skills/flutter.png",
      "../skills/firebase.png",
      "../skills/git.png",
    ],
    content:
      "Printing Vendo Machine is a self-service kiosk for printing, scanning, and saving documents via Wi-Fi or USB, with coin-based payment.",
    github: "https://github.com/Dave-Projects/Printing-Machine",
    live: "",
  },
  {
    pid: "2",
    name: "QUIZME",
    tagline: "Quiz system website",
    textcolor: "white",
    time: "2 weeks",
    color: "#19381f",
    cover_image: "../mockups/QuizMe.png",
    web_images: [
      "../projects/QuizMe.png",
      "../projects/Questions.png",
      "../projects/Results.png",
    ],
    mob_images: [
      "../projects/QuizMeMobile.jpg",
      "../projects/MobileQuestions.jpg",
      "../projects/MobileAnswers.jpg",
    ],

    tech_images: [
      "../skills/react.png",
      "../skills/html.png",
      "../skills/css.png",
      "../skills/js.png",
      "../skills/nodejs.png",
    ],
    content:
      "Developed and designed with Vite React js. The system dynamically manages quiz data using an API, supports various types of questions, and keeps track of user scores in real time.",
    github: "https://github.com/Dave-Projects/QuizMe",
    live: "https://quiz-me-teal.vercel.app/",
  },
  {
    pid: "3",
    name: "HCDC TOOLROOM",
    tagline: "Tool Room Application",
    color: "orange",
    textcolor: "white",
    time: "2 months",
    cover_image: "../mockups/TOOLROOM.png",
    web_images: [
      "../projects/BorrowTools.png",
      "../projects/ReturnTools.png",
      "../projects/Inventory.png",
      "../projects/Records.png",
      "../projects/Admin.png",
      "../projects/AddStudents.png",
    ],
    mob_images: [],

    tech_images: [
      "../skills/sharp.png",
      "../skills/mysql.png",
    ],
    content:
      "The HCDC Tool Room System streamlines tool borrowing and returns for students and faculty, ensuring organized inventory management. Utilized C#.NET and MYSQL database for this project.",
    github: "https://github.com/Dave-Projects/HCDC-Tool-Room",
  },
  {
    pid: "4",
    name: "Courserec",
    tagline: "Course recommendation website",
    time: "30 days",
    textcolor: "white",
    color: "grey",
    cover_image: "../mockups/CET.png",
    web_images: [
      "../projects/Course1.png",
      "../projects/Course2.png",
      "../projects/Course3.png",
      "../projects/Predict1.png",
      "../projects/Predict2.png",
    ],
    mob_images: [
    ],

    tech_images: [
      "../skills/php2.png",
      "../skills/python.png",
      "../skills/html.png",
      "../skills/css.png",
      "../skills/js.png",
      "../skills/sass.png",
    ],
    content:
      "A course recommendation platform that uses AI, helping students discover the best academic path according to their skills, interests, and career goals.",
    github: "https://github.com/Dave-Projects/Course-rec-Hci102-",
  },
  {
    pid: "5",
    name: "mygym",
    tagline: "Gym management app",
    color: "orange",
    textcolor: "white",
    time: "1 week",
    cover_image: "../mockups/mu_gym2.jpg",
    mob_images: [
      "../projects/mg1.jpg",
      "../projects/mg2.jpg",
      "../projects/mg3.jpg",
      "../projects/mg4.jpg",
      "../projects/mg5.jpg",
    ],
    tech_images: [
      "../skills/native.png",
      "../skills/js.png",
      "../skills/nodejs.png",
      "../skills/mongodb.png",
      "../skills/express.png",
    ],
    content:
      "Developed using react native. It offers functionalities to create an admin account and manage daily tasks of a gym",
    live: "",
    github: "",
  },

  {
    pid: "6",
    name: "PrintVendo(WebApp)",
    tagline: "A cryptocurrency price tracking app",
    color: "orange",
    time: "1 week",
    textcolor: "white",
    cover_image: "../mockups/PrintVendoUpload.png",
    mob_images: [
      "../projects/WebApp.jpg",
      "../projects/files.jpg",
      "../projects/uploadsuccessfully.jpg",
      "../projects/server.png",
    ],
    tech_images: [
      "../skills/python.png",
      "../skills/html.png",
      "../skills/css.png",
      "../skills/js.png",
      "../skills/express.png",
    ],
    content:
      "Developed and designed with Python. Website  for uploading files from a phone using a QR code scanner to the machine.",
    live: "",
    github: "",
  },
];
export { data };
